owner: emacuello
repo: upptime

sites:
    - name: Youdrive
      url: https://youdrive.vercel.app/
    - name: Emax-Peluquería
      url: https://emaxpeluqueria.vercel.app/
    - name: Emacommerce API
      url: $EMACOMMERCE_API_URL
    - name: Youdrive API
      url: $YOUDRIVE_API_URL
    - name: Emax-Peluquería API GATEWAY
      url: $EMAX_PELUQUERIA_API_URL
    - name: Emax-Peluquería API Microservices
      url: $EMAX_PELUQUERIA_API_URL_MS
    - name: Contact Form API
      url: $CONTACT_FORM_URL
    - name: Contact Form
      url: https://emacuello-contact.vercel.app/
    - name: Portfolio
      url: https://emacuello-portafolio.vercel.app/
    - name: Link
      url: https://emacuello.link
    - name: Emax-Peluquería Shop API
      url: $EMAX_PELUQUERIA_SHOP_API_URL

status-website:
    baseUrl: /upptime
    logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
    name: Upptime
    introTitle: 'Estos son los servidores que estoy monitorizando actualmente'
    introMessage: 'Soy Emanuel Cuello, Backend Developer & SRE. Está es la lista de servidores que actualmente estoy monitorizando con Upptime. Para cualquier consulta, por favor contacta conmigo en <a href="https://emacuello.link">Pagina Web</a> o <a href="https://www.linkedin.com/in/vcuellojrs/">Linkedin</a>.'
    navbar:
        - title: Status
          href: /
        - title: GitHub
          href: https://github.com/$OWNER/$REPO
        - title: Linkedin
          href: https://www.linkedin.com/in/vcuellojrs/
        - title: Web
          href: https://emacuello.link

i18n:
    history: 'Historial'
    responseTime: 'Tiempo de respuesta'
    activeIncidents: Incidentes activos
    allSystemsOperational: Todos los sistemas están operativos
